name: Build and Push Docker Image

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      actions: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete old package versions
        run: |
          echo "ðŸ§¹ Deleting old package versions..."
          PACKAGE="family-plan"
          OWNER="${{ github.repository_owner }}"
          TOKEN="${{ secrets.GITHUB_TOKEN }}"

          versions=$(curl -s -H "Authorization: Bearer $TOKEN" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/users/$OWNER/packages/container/$PACKAGE/versions" | jq -r '.[].id')

          if [ -z "$versions" ]; then
            echo "No old versions found."
          else
            for id in $versions; do
              echo "Deleting version ID: $id"
              curl -X DELETE -H "Authorization: Bearer $TOKEN" \
                -H "Accept: application/vnd.github+json" \
                "https://api.github.com/users/$OWNER/packages/container/$PACKAGE/versions/$id"
            done
          fi


      # - name: Generate UUID for tag
      #   id: uuid
      #   run: echo "UUID_TAG=$(uuidgen | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      # - name: Build and push Docker image
      #   uses: docker/build-push-action@v6
      #   with:
      #     context: .
      #     file: ./Dockerfile
      #     push: true
      #     tags: |
      #       ghcr.io/${{ github.repository_owner }}/family-plan:latest
      #       ghcr.io/${{ github.repository_owner }}/family-plan:${{ env.UUID_TAG }}

      # - name: Output image URL
      #   run: |
      #     echo "âœ… Image pushed:"
      #     echo " - ghcr.io/${{ github.repository_owner }}/family-plan:latest"
      #     echo " - ghcr.io/${{ github.repository_owner }}/family-plan:${{ env.UUID_TAG }}"
